apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperatura
spec:
  selector:
    matchLabels:
      app: temperatura
  template:
    metadata:
      labels:
        app: temperatura
    spec:
      containers:
        - name: temperatura
          image: matheustanure/conversao-temperatura:v1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: temperatura
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
